---

- name: Get ESC instance info
  os_server_facts:
    cloud: "{{ cloud_name }}"
    server: "{{ esc.name }}"

- name: Prepare for floating IP check
  set_fact:
    fip_exists: False

- name: Check if floating IP already assigned (by checking if management network has 2nd IP address defined)
  set_fact:
    fip_exists: True
  when: esc.management_floating is defined and openstack_servers[0].networks[instance.management_net][1] is defined

- name: Print Floating IP check information (if fip is already defined)
  debug:
    var: fip_exists
  when: esc.management_floating is defined 

- name: debug
  debug:
    var: openstack_servers

- name: Add floating IP to ESC instance (if not already defined)
  os_floating_ip:
    cloud: "{{ cloud_name }}"
    state: present
    reuse: Yes
    server: "{{ esc.name }}"
    network: "{{ pod.floating_network }}"
    fixed_address: "{{ openstack_servers[0].networks[instance.management_net][0] }}"
  when: esc.management_floating is defined and not fip_exists
  register: results
  changed_when: results.failed is not defined

- name: Pause for 5 seconds
  pause:
    seconds: 5
  when: results.changed

- name: Get ESC instance info
  os_server_facts:
    cloud: "{{ cloud_name }}"
    server: "{{ esc.name }}"

- name: Show assigned floating IP address
  debug:
    msg: "{{ openstack_servers[0].networks[instance.management_net][1] }}"
  when: esc.management_floating
  ignore_errors: True

...
