---

# Ansible playbook to test operations on the target POD
#

- name: Create test instance
  hosts: local
  gather_facts: False
  vars:
    cloud_name: paris

  roles:
    - { role: "instance-delete" }

...
