---

# Ansible playbook to test operations on the target POD
#

- name: Run all tests
  hosts: local
  gather_facts: False
  vars:
    cloud_name: paris

  roles:
    - { role: "openstack-setup" }

...
