---

# Ansible role to test basic tasks in OpenStack
#

- name: "Create flavor" 
  os_nova_flavor:
    cloud: "{{ cloud_name }}"
    state: present
    name: "{{ item.value.name }}"
    ram: "{{ item.value.ram }}"
    vcpus: "{{ item.value.vcpus }}"
    disk: "{{ item.value.disk }}"
    ephemeral: "{{ item.value.ephemeral | default(omit) }}"
  with_dict: "{{ flavors }}"

- name: "Delete flavor"
  os_nova_flavor:
    cloud: "{{ cloud_name }}"
    state: absent
    name: "{{ item.value.name }}"
  with_dict: "{{ flavors }}"

...
