---

- name: Download image
  get_url:
    url: "{{ image.download_url }}"
    dest: "{{ file_path }}{{ image.filename }}"
  when: image.download_url is defined

- name: Upload image to glance
  os_image:
    cloud: "{{ cloud_name }}"
    state: present
    name: "{{ image.name }}"
    disk_format: "{{ image.disk_format }}"
    container_format: "{{ image.container_format }}"
    filename: "{{ file_path }}{{ image.filename }}"
    properties: "{{ image.properties | default(omit) }}"

...
