---

- name: Get network IDs
  os_networks_facts:
    cloud: "{{ cloud_name }}"
    filters:
      name: "{{ item }}"
  register: nets
  with_items:
    - "{{ instance.management_net }}"
    - "{{ instance.inside_net }}"
    - "{{ instance.outside_net }}"
  loop_control:
    label: "{{ item }}"

- name: Map network IDs
  set_fact:
    network_id: "{{ network_id | default({}) | combine( {item.item: item.ansible_facts.openstack_networks[0].id} ) }}"
  with_items: "{{ nets.results }}"
  loop_control:
    label: "{{ item.item }}"  

- name: Launch instance
  os_server:
    cloud: "{{ cloud_name }}"
    state: present
    name: "{{ instance.name }}"
    image: "{{ instance.image }}"
    #key_name: "{{ os_key_pair }}"
    #security_groups: all
    flavor: "{{ instance.flavor }}"
    auto_ip: False
    config_drive: True
    userdata: "{{ instance.userdata | default(omit) }}"
    nics:
      - net-id: "{{ network_id[instance.management_net] }}"
        v4-fixed-ip: "{{ instance.management_ip | default({}) }}"
      - net-id: "{{ network_id[instance.inside_net] }}"
        v4-fixed-ip: "{{ instance.inside_ip | default({}) }}"
      - net-id: "{{ network_id[instance.outside_net] }}"
        v4-fixed-ip: "{{ instance.outside_ip | default({}) }}"
  register: instance_created

- name: Give instance some time to launch
  pause:
    seconds: 5
  when: instance_created.changed

...
