---

- debug:
    msg: "Variable files loaded: {{ title }}"
  tags:
    - always

- include: openrc.yaml
  tags: [openrc]

- include: user.yaml
  tags: [user]

- include: project.yaml
  tags: [project]

...
