---

projects:
  demo1:
    enabled: True
    description: "project - demo1"
  demo2:
    enabled: False
    description: "project demo2"

users:
  user1:
    password: pass1
    project: demo1
    enabled: True
    role_admin: False
    openrc: True
    openrc_name: /openstack-configs/openrc-demo1
  user2:
    password: pass2
    project: demo1
    enabled: True
    role_admin: True
    openrc: True
    openrc_name: /openstack-configs/openrc-demo1user2
  user3:
    password: pass3
    project: demo2
    enabled: True
    role_admin: False
    openrc: False

openrc:
  file_owner: root
  file_group: root

...
