---

# Ansible playbook to test operations on the target POD
#

- name: Cleanup
  hosts: local
  gather_facts: False
  vars_files:
    - /ansible/playbooks/setup.yaml

  roles:
    - { role: "openstack-cleanup" }

...
