---

# Ansible playbook to test operations on the target POD
#

- name: Run all tests
  hosts: local
  gather_facts: False
  vars_files:
    - /ansible/playbooks/config/setup.yaml

  roles:
    - { role: "openstack-setup" }

...
