---

# Ansible playbook to delete projects, users and remove roles in NFVI POD
#

- name: Delete OpenStack projects/users/roles
  hosts: local
  gather_facts: False
  vars_files:
    - /ansible/playbooks/config/setup.yaml
    - /ansible/playbooks/config/projects.yaml

  roles:
    - { role: "project-delete" }

...
